# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b1908a5931d1c99a81382bec1166a6a071ac993236c69b3b20bbea2e910b0e1e95fba74b3f7b96c4f2bf45c0c44cebac461d52b2224a673aad2f847c56532c5

test:
  secret_key_base: 3302872da688f6179c5cb5d6ff51901a892db2eb17a42db3a13784d119ef59ed1ec8ff006acf27935f2c7e95de035af6066f98d3a567fe0fbadc7f4f143913d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
